hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}_two_lora-overfit-no_all
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metric.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."
#128
batch_size: 128
increment: 10
initial_increment: 10
scenario: "class"
dataset: "cifar100"
task_num: 10
seed: 42

epochs: 1
train_batch_size: 128
num_workers: 8
lora_rank: 8
lora_mode: "vision+only_kv+text"
lr: 0.001
reset: False
only_reset_B: False
freeze_A: False
all_test: False


visual_agent: true
visual_agent_lr: 0.0005
visual_agent_batch_size: 64
visual_agent_epochs: 3



real_replay: false
balance_ft: False
balance_epochs: 0
