hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metric.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 32
initial_increment: 20
increment: ${initial_increment}
scenario: "class"
dataset: "imagenet_R"
task_num: 10

epochs: 2
# 64
train_batch_size: 64
num_workers: 8
lora_rank: 8
lora_mode: "vision+only_kv+text"
lr: 0.001
reset: False
only_reset_B: False
freeze_A: False
all_test: False
weight_decay: 1e-4
momentum: 0.9
seed: 0


visual_agent: true
visual_agent_lr: 0.0005
visual_agent_batch_size: 32
visual_agent_epochs: 3

real_replay: false


balance_ft: False
balance_epochs: 1

